"""empty message

Revision ID: 8e246edd551b
Revises: a88415a2ec7b
Create Date: 2020-03-02 22:52:59.971846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e246edd551b'
down_revision = 'a88415a2ec7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
