"""empty message

Revision ID: a88415a2ec7b
Revises: adc1aa6daf9f
Create Date: 2020-03-02 22:24:05.597751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a88415a2ec7b'
down_revision = 'adc1aa6daf9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'last',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
